### ISSUE TITLE
Diseño del logo

### ISSUE THREAD

**Issue by manuel-ruiz-23** [manuel-ruiz-23/abastobarrial#1]
Ya se esta trabajando en el Logo, Gracias Sara!!!

![WhatsApp Image 2020-04-06 at 6 47 15 PM](https://user-images.githubusercontent.com/16631761/78625291-8bfbda80-7840-11ea-80a8-bd127522c554.jpeg)
![WhatsApp Image 2020-04-06 at 6 46 48 PM](https://user-images.githubusercontent.com/16631761/78625294-8d2d0780-7840-11ea-86aa-51aa22038a19.jpeg)

**Comment by celerno** [comment]
tenemos los archivos de cada logo de estos?

**Comment by manuel-ruiz-23** [comment]
no y  de echo el logo que esta en los mocks es diferente, tiene color, ya se lo encarge a sara, hoy le recordare a ver que ondas, por mientras podemos usar un recorte del mock en lo que tenemos en svg o png

**Comment by manuel-ruiz-23** [comment]
![image](https://user-images.githubusercontent.com/16631761/82129609-60dea200-9781-11ea-89bc-db7610d2e39b.png)
 Logo final!!
